version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    privileged: true

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://139.59.35.228:3000
    privileged: true

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9101:9100"
    privileged: true

volumes:
  grafana-storage:

